#!/bin/bash
sudo yum remove httpd* php*
sudo yum clean all
sudo yum update -y
sudo yum install httpd -y
sudo yum install php72 --skip-broken
sudo service httpd restart
sudo chkconfig httpd on
yum install -y php72-gd php72-xml php72-xmlrpc php72-mcrypt php-pear --skip-broken
sudo yum install php72-cli php72-xml php72-json php72-mbstring php72-process php72-common php72-fpm php72-zip php72-mysqlnd git -y
sudo yum install git -y
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/bin/composer
chmod +x /usr/bin/composer
cd /var/www
git clone https://github.com/engr-usman/laravel.git
cd /var/www/laravel
COMPOSER_MEMORY_LIMIT=-1 composer install
sudo chown -R ec2-user:apache /var/www
sudo chmod 2775 /var/www && find /var/www -type d -exec sudo chmod 2775 {} \;
find /var/www -type f -exec sudo chmod 0664 {} \;
cd /var/www/laravel
cp .env.example .env
php artisan key:generate
sudo service httpd restart